package com.example.noahrickles.waterreporterteam14_harambelovedwaters.model;

/**
 * Created by Matt on 2/27/2017.
 */

public class WaterReport {

    private String dateAndTime;
    private String location;
    private String username;
    private int reportNumber = 0;
    private String typeOfWater;
    private String conditionOfWater;

    /**
     * Constructor for the water report object
     * @param dateAndTime       A String representation of the current date and time of the report
     * @param location          The location of the water
     * @param username          The user submitting the report
     * @param reportNumber      Autogenerated report number
     * @param typeOfWater       The type of the water source
     * @param conditionOfWater  The drinking condition of the water
     */
    public WaterReport(String dateAndTime, String location, String username,
                       int reportNumber, String typeOfWater, String conditionOfWater) {
        this.dateAndTime = dateAndTime;
        this.location = location;
        this.username = username;
        this.reportNumber = reportNumber;
        this.typeOfWater = typeOfWater;
        this.conditionOfWater = conditionOfWater;
    }

    /**
     * Gets the date and time of a WaterReport
     * @return the WaterReport's dateAndTime
     */
    public String getDateAndTime() {
        return dateAndTime;
    }

    /**
     * Gets the location of a WaterReport
     * @return the WaterReport's location
     */
    public String getLocation() {
        return location;
    }

    /**
     * Gets the username of a WaterReport
     * @return the WaterReport's username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Gets the report number of a WaterReport
     * @return the WaterReport's reportNumber
     */
    public int getReportNumber() {
        return reportNumber;
    }

    /**
     * Gets the type of water of a WaterReport
     * @return the WaterReport's typeOfWater
     */
    public String getTypeOfWater() {
        return typeOfWater;
    }

    /**
     * Gets the condition of water of a WaterReport
     * @return the WaterReport's conditionOfWater
     */
    public String getConditionOfWater() {
        return conditionOfWater;
    }

    /**
     * Gets a String representation of the WaterReport, including important
     * information about the WaterReport.
     * @return the String representation of the User
     */
    public String toString() {
        return "Date/Time: " + dateAndTime + "\nLocation: " + location + "\nSubmitter: " +
                username + "\nReport number: " + reportNumber + "\nType of Water: " +
                typeOfWater + "\nCondition of Water: " + conditionOfWater;
    }

}
