package com.example.noahrickles.waterreporterteam14_harambelovedwaters.model;

/**
 * Created by Matt on 2/27/2017.
 */

public class WaterReport {

    private String dateAndTime;
    private String location;
    private String username;
    private int reportNumber = 0;
    private String typeOfWater;
    private String conditionOfWater;

    /**
     * Constructor for the water report object
     * @param dateAndTime A String representation of the current date and time of the report
     * @param location The location of the water
     * @param username The user submitting the report
     * @param reportNumber Autogenerated report number
     * @param typeOfWater The type of the water source
     * @param conditionOfWater The drinking condition of the water
     */
    public WaterReport(String dateAndTime, String location, String username,
                       int reportNumber, String typeOfWater, String conditionOfWater) {
        this.dateAndTime = dateAndTime;
        this.location = location;
        this.username = username;
        this.reportNumber = reportNumber;
        this.typeOfWater = typeOfWater;
        this.conditionOfWater = conditionOfWater;
    }

    public String getDateAndTime() {
        return dateAndTime;
    }

    public String getLocation() {
        return location;
    }

    public String getUsername() {
        return username;
    }

    public int getReportNumber() {
        return reportNumber;
    }

    public String getTypeOfWater() {
        return typeOfWater;
    }

    public String getConditionOfWater() { return conditionOfWater; }

    public String toString() {
        return "Date/Time: " + dateAndTime + "\nLocation: " + location + "\nSubmitter: " +
                username + "\nReport number: " + reportNumber + "\nType of Water: " +
                typeOfWater + "\nCondition of Water: " + conditionOfWater;
    }

}
